version: '3.8'
services:
  backend:
    build:
      context: ..
    ports:
      - "8080:8080"
    container_name: krazytop-back

  frontend:
    build:
      context: ../../krazytop-front
    ports:
      - "4200:80"
    container_name: krazytop-front

  mongodb:
    image: mongo:7.0.2
    ports:
      - "27018:27017"
    container_name: krazytop-mongodb

  nginx:
    build:
      context: ../../krazytop-front
      dockerfile: ../../krazytop-front/Dockerfile-nginx
    ports:
      - "80:80"