version: '3.8'
services:
  backend:
    build:
      context: https://github.com/krazytop/Krazytop.gg-Backend
      dockerfile: Dockerfile-Backend
    ports:
      - "8080:8080"
    container_name: krazytop-back

  frontend:
    build:
      context: https://github.com/krazytop/Krazytop.gg-Frontend
      dockerfile: Dockerfile-Frontend
    ports:
      - "4200:80"
    container_name: krazytop-front

  nginx:
    build:
      context: https://github.com/krazytop/Krazytop.gg-Frontend
      dockerfile: Dockerfile-Nginx
    ports:
      - "80:80"