server:
  port: 8080
spring:
  security:
    user:
      name: krazytop
      password: password
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      tft:
        uri: ${MONGO_DATABASE_URL}TeamfightTactics
      lol:
        uri: ${MONGO_DATABASE_URL}LeagueOfLegends
      clash-royal:
        uri: ${MONGO_DATABASE_URL}ClashRoyal
      api-key:
        uri: ${MONGO_DATABASE_URL}ApiKey
    web:
      pageable:
        default-page-size: 30
    bungie:
      client_id: ${BUNGIE_CLIENT_ID}
      client_secret: ${BUNGIE_CLIENT_SECRET}
