server:
  port: 8080
spring:
  security:
    user:
      name: krazytop
      password: password
  data:
    mongodb:
      tft:
        uri: mongodb+srv://krazytop:QzbZDXfMzxDL1D9D@krazytop.qab5sau.mongodb.net/TeamfightTactics
      lol:
        uri: mongodb+srv://krazytop:QzbZDXfMzxDL1D9D@krazytop.qab5sau.mongodb.net/LeagueOfLegends
      riot:
        uri: mongodb+srv://krazytop:QzbZDXfMzxDL1D9D@krazytop.qab5sau.mongodb.net/Riot
      clash-royal:
        uri: mongodb+srv://krazytop:QzbZDXfMzxDL1D9D@krazytop.qab5sau.mongodb.net/ClashRoyal
      destiny:
        uri: mongodb+srv://krazytop:QzbZDXfMzxDL1D9D@krazytop.qab5sau.mongodb.net/Destiny
    web:
      pageable:
        default-page-size: 5