server:
  port: 8080
spring:
  security:
    user:
      name: krazytop
      password: password
  data:
    mongodb:
      tft:
        uri: ${MONGO_DATABASE_URL}/TeamfightTactics
      lol:
        uri: ${MONGO_DATABASE_URL}/LeagueOfLegends
      riot:
        uri: ${MONGO_DATABASE_URL}/Riot
      clash-royal:
        uri: ${MONGO_DATABASE_URL}/ClashRoyal
      destiny:
        uri: ${MONGO_DATABASE_URL}/Destiny
    web:
      pageable:
        default-page-size: 5