name: Build Java Project with Maven and Generate JAR

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.APP_ENGINE_DEPLOY_KEY }}'

      - name: Deploy to App Engine
        id: deploy
        run: |  # Corrected command using shell syntax
          gcloud app deploy target/krazytop-back-1.0-SNAPSHOT.jar \
            --runtime java20
            --project krazytop
            --url https://krazytop.com
