openapi: 3.0.0
info:
  title: Global API Gateway
  version: 1.0.0
  description: Central API

servers:
  - url: http://localhost:8080
    description: Local Development API Gateway
  - url: https://api.krazytop.com
    description: Production API Gateway

tags:
  - name: Destiny
    description: Operations related to Destiny 2.
  - name: Authentification
    description: Operations related to user authentication.

paths:
  /destiny/auth/{code}:
    $ref: './controllers/destiny/destiny-auth.yaml#/getPlayerToken'
  /destiny/auth:
    $ref: './controllers/destiny/destiny-auth.yaml#/updatePlayerToken'

components:
  schemas:
    ApiError:
      $ref: './models/ApiError.yaml'